Add basic Airy function bindings
Nemocas/Nemo.jl pull request #1096
Opened 2021-06-22 11:05 UTC by Vectornaut

Function names are provisional. I've run informal tests against the SpecialFunctions package, but I need guidance on how to write formal tests.

These bindings only compute individual Airy functions and derivatives. It might be nice to add more bindings that take advantage of Arb's simultaneous computation feature.

I don't know how to preview the new docstrings, so they may have Markdown or LaTeX errors.

2021-06-22 13:46 UTC, thofma commented
Is it possible to add some tests? Does not need to be complicated, just to make sure that the functions don't crash.

(@tthsqe12 @albinahlback What do you think of those names?)

2021-06-22 14:47 UTC, tthsqe12 requested changes
Names are great. Just need some test code to make sure the code doesn't crash and that it calls the right functions.

2021-06-22 15:13 UTC, albinahlback commented on src/arb/arb.jl
> +################################################################################
Maybe it is a good idea to have more sections within the file, but then I would expect the same for `acb.jl`.

2021-06-22 15:13 UTC, albinahlback commented
Looks good to me, but of course needs some tests.

2021-06-22 15:34 UTC, albinahlback commented
As for the tests: For `airy_ai` with `arb` arguments, I would go to about line 337 in `/test/arb/arb-test.jl` and append the respective tests, where the second argument in `overlaps` is the returned value when calculating the function at about twice the precision (100 bit precision should be just fine).

As Tommy implied (and correct me if I am wrong), the tests in Nemo are there only to ensure that the returned value is stable. It is Arb's task to ensure that they are correct.

2021-06-24 12:41 UTC, wbhart commented
The tests in Nemo are currently pretty inadequate on the whole. I think they should test:

* that the binding are working (i.e. call the actual function at least once)
* corner cases
* that the documentation for Nemo matches what the function actually does
* DomainErrors and other exceptions are thrown as appropriate

Obviously if the function is not a straightforward wrapper and needs to do some computation, that should be tested as well as stuff in AbstractAlgebra.

But yes, it is Arb's responsibility to ensure the result is correct, assuming correct input is passed.

2021-06-29 13:06 UTC, thofma commented
We will merge it as is and @tthsqe12 will add the missing tests.

2021-06-29 13:06 UTC, merged