Wrap Flint's tstbit
Nemocas/Nemo.jl pull request #1158
Opened 2021-08-11 16:52 UTC by wbhart

Fixes #715

2021-08-11 17:48 UTC, rfourquet commented on src/flint/fmpz.jl
> +Test bit $i$ of x (numbered from 0) and return 1 or 0 depending if it is set.
Maybe return a `Bool`? As `Bool <: Integer`, the result can still be used as an integer, but also as a condition e.g. in an `if` statement.

2021-08-13 14:03 UTC, wbhart commented
I'm just following the flint and GMP naming convention here. This is a pretty low level function which isn't going to get much use, so I figure the name isn't too important.

2021-09-09 09:27 UTC, tthsqe12 commented on src/flint/fmpz.jl
> +      return 0
```suggestion
      return false
```
Also maybe some test code for this with @ inferred ?

2021-09-09 09:30 UTC, tthsqe12 requested changes

2021-09-09 09:30 UTC, tthsqe12 commented on src/flint/fmpz.jl
> +Test bit $i$ of x (numbered from 0) and return 1 or 0 depending if it is set.
```suggestion
Return the $i$^th bit of x (numbered from 0) as `true` for 1 or `false` for 0.
```

2021-09-26 14:57 UTC, thofma commented
Sorry, this needs a rebase.

2021-09-27 14:32 UTC, closed without merging