Add gfp_abs_series sqrt functions and deal with char 2
Nemocas/Nemo.jl pull request #1261
Opened 2022-01-24 17:12 UTC by wbhart

I think this is ok without flint-2.9 but let's wait to see what CI says.

2022-01-26 15:05 UTC, wbhart commented
Test failures appear to be doctests unrelated to this PR.

2022-01-28 16:56 UTC, tthsqe12 requested changes

2022-01-28 16:56 UTC, tthsqe12 commented on test/flint/gfp_abs_series-test.jl
> +         end
```suggestion
         end

         if mod(p, 4) == 3
            @test !issquare(-one(S))
         end
```

2022-01-28 16:56 UTC, tthsqe12 commented on test/flint/gfp_abs_series-test.jl
> +         end
for test coverage :)

2022-01-28 16:56 UTC, tthsqe12 commented on test/flint/gfp_abs_series-test.jl
> +         end
other than that, fine by me

2022-01-28 17:20 UTC, merged