Remove Pkg from dependencies
Nemocas/Nemo.jl pull request #1896
Opened 2024-10-13 11:32 UTC by sumiya11

A PR for #1895. 

I don't know if `Base.get_pkgversion_from_path` covers all the cases that were previously handled.

2024-10-13 17:06 UTC, lgoettgens requested changes
This does not work on julia 1.6 (the compat bound of Nemo)

2024-10-13 17:36 UTC, sumiya11 commented
Would it be reasonable to do `if VERSION < 1.11 then "old version()" else "new version()" end` ?

2024-10-13 17:51 UTC, lgoettgens commented
`Base.get_pkgversion_from_path` is non-public, so shouldn't be relied on

2024-10-14 13:34 UTC, fingolfin commented on src/Nemo.jl
> +version() = Base.get_pkgversion_from_path(pkgdir)
In Oscar.jl we instead use this code to determine if it is a dev version (but this is also far from perfect -- and it uses `Pkg`):
```
const is_dev = (function()
        deps = Pkg.dependencies()
        if Base.haskey(deps, PROJECT_UUID)
          if deps[PROJECT_UUID].is_tracking_path
            return true
          end
        end
        return occursin("-dev", lowercase(string(VERSION_NUMBER)))
    end)()
```

2024-10-15 06:39 UTC, fingolfin commented
@sumiya11 I have no idea and in any case, none of this is documented AFAIK. I am not concerned with imitating current behavior 1-1. Rather, the general idea, which is to be able to detect reliably which version a user reporting an issue really is using: i.e. either a specific stable release, and which; or some git version (ideally identified by commit). Just like the Julia banner does (perhaps one could look at its current code for inspiration).

2024-10-15 10:30 UTC, sumiya11 commented
> I am not concerned with imitating current behavior 1-1. Rather, the general idea, which is to be able to detect reliably which version a user reporting an issue really is using: i.e. either a specific stable release, and which; or some git version (ideally identified by commit). Just like the Julia banner does (perhaps one could look at its current code for inspiration).

Thank you for the clarification.

If so, why not ask the user for the output of `Pkg.status()` instead of relying on the error-prone `version` ?

2024-10-15 11:24 UTC, thofma commented
It is mainly for the banner which includes the version number. Maybe they fix the Pkg loading regression in 1.11.1. It is not the only thing that got slower.

2024-12-07 12:14 UTC, closed without merging