Lattice of finite fields fixed
Nemocas/Nemo.jl pull request #916
Opened 2020-11-20 14:38 UTC by CarloSircana

2020-11-20 15:11 UTC, thofma approved these changes

2020-11-20 15:22 UTC, wbhart requested changes

2020-11-20 15:22 UTC, wbhart commented on src/embedding/embedding.jl
> +#This function assumes that f has been created as a result of the embed_matrices
Could we just remove the old version? Or is there something worth keeping that isn't implemented in the new version?

2020-11-20 15:22 UTC, wbhart commented on src/embedding/embedding.jl
> +
There are quite a few blank lines after prototypes here. I realise they were there in the original, but perhaps they can be removed, as we don't do that anywhere else.

2020-11-20 15:23 UTC, wbhart commented
This looks good. I'm not sure how the original was working given the obvious problems with it. Or, I suppose that is the point of the PR. Thanks @CarloSircana

2020-11-23 08:50 UTC, CarloSircana commented
Some tests are failing, but they are not related to my changes...

2020-11-23 12:59 UTC, thofma commented
Yes, the failure is not related to your changes.

I marked this PR as breaking, since it changes the types, so anyone using them needs to adjust the code. This just means we will merge it once we decide to make the next breaking release.

2020-11-23 14:34 UTC, erou commented
Hi @CarloSircana, thank you very much for all the types mistakes and inaccuracies that you eliminated! I was not too sure about it when I wrote the code.

I am intrigued by some changes you made, maybe you could help me understand. I am still working on related topics, that's why I would be very interested if you caught something that I did not think about or implemented in a poor way.

- I am not too sure about your second set of tests (``@testset "embedding-lattice" begin`` and after), it seems to me that it does something similar to what is already done in the file ``flint/fq_nmod_embed-test.jl``.
- You changed the way the minimal polynomial was computed and I have two interrogations: one is about the performance, does it change something? The second is about the reasons behind the change: I do not really get why you wanted to change it, can you do something with the new code that you were not able to with the old one?
- In ``AddOverfield!`` and ``AddSubfield!``, you added changes to make sure that the added morphism is not already there. It seems to me that this is never the case because these functions are supposed to be called at times where the morphism is indeed missing (in the functions ``transitive_close`` and ``embed``). But maybe I am wrong and you did find some bugged cases?
- in ``isembedded`` you check both the subfields of `K` and the overfields of `k`, but I think that if `k` is embedded into `K`, the embedding is supposed to be in both dictionaries, thus there is no need to check both of them, one is enough.

Thank you again for your work.

2022-02-02 19:48 UTC, closed without merging